repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.12
  hooks:
    - id: ruff
    - id: ruff-format

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: __init__.py
        args: [ --profile, black, --filter-files ]